plugins:
  weekly_email_report_enabled:
    default: true
  weekly_email_report_recipients:
    default: "test@example.com"
  weekly_email_report_interval:
    default: 7
  weekly_email_report_compliance:
    default: 240
  weekly_email_report_top_user_count:
    default: 5
  weekly_email_report_day_of_week:
    default: "Monday"
  weekly_email_report_time_of_day:
    default: "6:00"
  weekly_email_report_show_empty_results:
    default: false
  weekly_email_report_domain:
    default: "https://example.com"
  weekly_email_report_subject:
    default: "Discourse metrics"